Problema 02
========================================================
Quais paí­ses tem os artistas mais populares/familiares por estilo?
--------------------------------------------------------
Para gerar essa visualização separei os artistas de acordo com seu paí­s e calculei a media de popularidade e familiaridade de cada paí­s.
```{r include= FALSE}
webplot = function(data, data.row = NULL, y.cols = NULL, main = NULL, add = F, 
                   col = "red", lty = 1, scale = T) {
  if (!is.matrix(data) & !is.data.frame(data)) 
    stop("Requires matrix or data.frame")
  if (is.null(y.cols)) 
    y.cols = colnames(data)[sapply(data, is.numeric)]
  if (sum(!sapply(data[, y.cols], is.numeric)) > 0) {
    out = paste0("\"", colnames(data)[!sapply(data, is.numeric)], "\"", 
                 collapse = ", ")
    stop(paste0("All y.cols must be numeric\n", out, " are not numeric"))
  }
  if (is.null(data.row)) 
    data.row = 1
  if (is.character(data.row)) 
    if (data.row %in% rownames(data)) {
      data.row = which(rownames(data) == data.row)
    } else {
      stop("Invalid value for data.row:\nMust be a valid rownames(data) or row-index value")
    }
  if (is.null(main)) 
    main = rownames(data)[data.row]
  if (scale == T) {
    data = scale(data[, y.cols])
    data = apply(data, 2, function(x) x/max(abs(x)))
  }
  data = as.data.frame(data)
  n.y = length(y.cols)
  min.rad = 360/n.y
  polar.vals = (90 + seq(0, 360, length.out = n.y + 1)) * pi/180
  
  # 
  if (add == F) {
    plot(0, xlim = c(-2.2, 2.2), ylim = c(-2.2, 2.2), type = "n", axes = F, 
         xlab = "", ylab = "")
    title(main)
    lapply(polar.vals, function(x) lines(c(0, 2 * cos(x)), c(0, 2 * sin(x))))
    lapply(1:n.y, function(x) text(2.15 * cos(polar.vals[x]), 2.15 * sin(polar.vals[x]), 
                                   y.cols[x], cex = 0.8))
    
    lapply(seq(0.5, 2, 0.5), function(x) lines(x * cos(seq(0, 2 * pi, length.out = 100)), 
                                               x * sin(seq(0, 2 * pi, length.out = 100)), lwd = 0.5, lty = 2, col = "gray60"))
    lines(cos(seq(0, 2 * pi, length.out = 100)), sin(seq(0, 2 * pi, length.out = 100)), 
          lwd = 1.2, col = "gray50")
  }
  
  
  r = 1 + data[data.row, y.cols]
  xs = r * cos(polar.vals)
  ys = r * sin(polar.vals)
  xs = c(xs, xs[1])
  ys = c(ys, ys[1])
  
  lines(xs, ys, col = col, lwd = 2, lty = lty)
  
}
```
```{r include= FALSE}
familiaridade_pais <- read.csv("~/ufcg/analise-de-dados-2/analise-de-dados-2-p2/familiaridade_pais1.csv")
popularidade_pais <- read.csv("~/ufcg/analise-de-dados-2/analise-de-dados-2-p2/popularidade_pais1.csv")
```
```{r fig.width=9, fig.height=9, echo=FALSE}
webplot(familiaridade_pais,1, main = "Familiaridade", scale = T)
par(new = T)
webplot(familiaridade_pais,2, col = "blue", main = "", scale = T)
par(new = T)
webplot(familiaridade_pais,3, col = "green", main = "", scale = T)
par(new = T)
webplot(familiaridade_pais,4, col = "yellow", main = "", scale = T)
par(new = T)
webplot(familiaridade_pais,5, col = "orange", main = "", scale = T)
legend("topright", lwd = 5, col = c("red", "blue", "green","yellow","orange"), c("Canada","France", "Jamaica", "United Kingdom", "United States"), bty = "n")
```

Com este gráfico fica fácil perceber quais paí­ses tem os artistas mais familiares mas fica difí­cil comparar os valores de um só pais então gerei a seguinte visualização:

```{r fig.width=9, fig.height=9, echo=FALSE}
## Segment Diagrams:
require(grDevices)
palette(rainbow(12, s = 0.6, v = 0.75))
stars(familiaridade_pais[, 2:6], key.loc = c(5.3, 2.3), len = 1, main = "Familiaridade", draw.segments = TRUE, full = FALSE, labels = c("Canada","France","Jamaica","United Kingdom","United States",""), scale = TRUE)
```

```{r fig.width=9, fig.height=9, echo=FALSE}
webplot(popularidade_pais,1, main = "Popularidade")
par(new = T)
webplot(popularidade_pais,2, col = "blue", main = "")
par(new = T)
webplot(popularidade_pais,3, col = "green", main = "")
par(new = T)
webplot(popularidade_pais,4, col = "yellow", main = "")
par(new = T)
webplot(popularidade_pais,5, col = "orange", main = "")
legend( "topright", lwd = 5, col = c("red", "blue", "green","yellow","orange"), c("Canada","France", "Jamaica", "United Kingdom", "United States"), bty = "n")
```

Com este gráfico fica fácil perceber quais paí­ses tem os artistas mais populares mas fica difí­cil comparar os valores de um só pais então gerei a seguinte visualização:

```{r fig.width=9, fig.height=9, echo=FALSE}
## Segment Diagrams:
require(grDevices)
palette(rainbow(12, s = 0.6, v = 0.75))
stars(popularidade_pais[, 2:6], key.loc = c(5.3, 2.3), main = "Popularidade", draw.segments = TRUE, full = FALSE, labels =c("Canada","France","Jamaica","United Kingdom","United States",""), scale = TRUE)
```

Depois de observar os gráficos percebemos que o paí­s que tem os artistas mais populares e familiares é o Reino Unido.

Quais os gêneros produzem mais músicas ao longo das décadas?
--------------------------------------------------------

Para gerer essa visualização combinei os dados de musicas com termos e agrupei em décadas para assim ter a contagem de musicas para cada uma delas.

```{r include = FALSE}
library(plyr)
library(ggplot2)
## Importando dados de artistas
subset_unique_artists <- read.csv("~/ufcg/analise-de-dados-2/analise-de-dados-2-p2/subset_unique_artists.csv")
## Importando dados de musicas
songs <- read.csv("~/ufcg/analise-de-dados-2/analise-de-dados-2-p2/songs.csv")
## Removendo dados com anos invalidos
songs <- subset(songs, songs$year > 0)
## Importando dados de termos
artists.terms <- read.csv("~/ufcg/analise-de-dados-2/analise-de-dados-2-p2/artist_term.csv")
## Merge de dados de musicas e termos
songs <- merge(songs,artists.terms,by="artist_id")
## Selecionando os ritmos 
songs <- subset(songs, songs$term == "rock" | songs$term == "jazz" | songs$term == "pop" | songs$term == "electronic" | songs$term == "alternative rock")
## Retirando colunas indesejadas
songs$artist_familiarity <- NULL
songs$artist_hotttnesss <- NULL
songs$duration <- NULL
songs$artist_name <- NULL
songs$artist_id <- NULL
songs$track_id <- NULL
songs$title <- NULL
songs$song_id <- NULL
songs$release <- NULL
songs$artist_mbid <- NULL
## Agrupando por decadas
toDecada <- function(x) {
  output <- x
  for(i in 1:nrow(x)) {
    row <- x[i,]
    if(row$year > 1919 && row$year < 1930) {
      output[i,]$year <- 1920
    } else if(row$year > 1929 && row$year < 1940) {
      output[i,]$year <- 1930
    } else if(row$year > 1939 && row$year < 1950) {
      output[i,]$year <- 1940
    } else if(row$year > 1949 && row$year < 1960) {
      output[i,]$year <- 1950
    } else if(row$year > 1959 && row$year < 1970) {
      output[i,]$year <- 1960
    } else if(row$year > 1969 && row$year < 1980) {
      output[i,]$year <- 1970
    } else if(row$year > 1979 && row$year < 1990) {
      output[i,]$year <- 1980
    } else if(row$year > 1989 && row$year < 2000) {
      output[i,]$year <- 1990
    } else if(row$year > 1999 && row$year < 2010) {
      output[i,]$year <- 2000
    } else if(row$year > 2009) {
      output[i,]$year <- 2010
    }
    print(output[i,]$year)
  }
  return(output)
}
songs <- toDecada(songs)
#Contando a frequencia de musicas por decada e termo
songs <- count(songs, c("term","year"))
#Criando escadas
escala <- c(1,5,10,30,50,100,200,300,400,500,1000,1500)
escala1 <- c(1920,1930,1940,1950,1960,1970,1980,1990,2000,2010)
```

```{r fig.width=12, fig.height=9, echo=FALSE}
#plote do grafico
ggplot(data=songs, aes(x=year, y=freq, fill=term)) + 
  geom_bar(colour= "black",stat="identity", position=position_dodge(), size=0.5) + # Thinner lines
  scale_fill_hue(name="Ritmos") +      # Set legend title
  scale_y_log10(breaks = escala) + # Set  y scale
  scale_x_log10(breaks = escala1) + # Set x scale
  xlab("Decada") +
  ylab("Quantidade de músicas") +
  ggtitle("Quantidade de músicas por década") +  # Set title
  theme_bw()
```

Fica fácil de perceber no gráfico que o gênero quem mais produz musica é o Rock